"""Static fund metadata used by :mod:`config.fund_registry`."""
from __future__ import annotations

from typing import Any, Dict

# The metadata below replaces the legacy SQL-backed registry. Each entry mirrors the
# columns that previously lived in ``fund_recon_mappings`` while surfacing additional
# descriptive properties that downstream services can query directly.
FUND_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "DOGG": {
        "custodian_equity_holdings": "bny_us_holdings_v2",
        "custodian_option_holdings": "bny_us_holdings_v2",
        "custodian_treasury_holdings": "bny_us_holdings_v2",
        "custodian_navs": "bny_us_nav_v2",
        "cash_table": "bny_us_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": "tif_frwd_data",
        "flows": "etf_flows",
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": None,
        "expense_ratio": 0.0075,
        "option_roll_tenor": "weekly",
        "overwrite": 0.08,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "etf",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": False,
        "flex_option_type": "single_stock",
        "has_otc": False,
        "has_treasury": True,
    },
    "FDND": {
        "custodian_equity_holdings": "bny_us_holdings_v2",
        "custodian_option_holdings": "bny_us_holdings_v2",
        "custodian_treasury_holdings": "bny_us_holdings_v2",
        "custodian_navs": "bny_us_nav_v2",
        "cash_table": "bny_us_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": "tif_frwd_data",
        "flows": "etf_flows",
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "DJINET",
        "expense_ratio": 0.0075,
        "option_roll_tenor": "weekly",
        "overwrite": 0.08,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "etf",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": False,
        "flex_option_type": None,
        "has_otc": False,
        "has_treasury": True,
    },
    "FGSI": {
        "custodian_equity_holdings": "bny_us_holdings_v2",
        "custodian_option_holdings": "bny_us_holdings_v2",
        "custodian_treasury_holdings": "bny_us_holdings_v2",
        "custodian_navs": "bny_us_nav_v2",
        "cash_table": "bny_us_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": "tif_frwd_data",
        "flows": "etf_flows",
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "nasdaq_pro",
        "index_ticker_join": "FGSI",
        "expense_ratio": 0.0085,
        "option_roll_tenor": "weekly",
        "overwrite": 0.08,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "etf",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": False,
        "flex_option_type": None,
        "has_otc": False,
        "has_treasury": True,
    },
    "FTCSH": {
        "custodian_equity_holdings": "bny_vit_holdings",
        "custodian_option_holdings": "bny_vit_holdings",
        "custodian_treasury_holdings": None,
        "custodian_navs": "bny_vit_nav",
        "cash_table": "bny_vit_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "nasdaq_pro",
        "index_ticker_join": "FTCSH",
        "expense_ratio": 0.0125,
        "option_roll_tenor": "quarterly",
        "overwrite": 0.0,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "vit",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": False,
        "flex_option_type": None,
        "has_otc": False,
        "has_treasury": False,
    },
    "FTMIX": {
        "custodian_equity_holdings": None,
        "custodian_option_holdings": "umb_ftmix_px",
        "custodian_treasury_holdings": None,
        "custodian_navs": "umb_ftmix_nav",
        "cash_table": "sg_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": None,
        "expense_ratio": 0.0225,
        "option_roll_tenor": "monthly",
        "overwrite": 0.0,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "mutual_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": False,
        "flex_option_type": None,
        "has_otc": False,
        "has_treasury": False,
    },
    "HE3B1": {
        "custodian_equity_holdings": "umb_cef_px",
        "custodian_option_holdings": "umb_cef_px",
        "custodian_treasury_holdings": None,
        "custodian_navs": "umb_cef_nav",
        "cash_table": "umb_cef_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "SPXFIOUP",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.12,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "closed_end_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": True,
        "flex_option_type": "index",
        "has_otc": False,
        "has_treasury": False,
        "overlap_table": "overlap_test",
        "overlap_benchmark_ticker": "SPY",
    },
    "HE3B2": {
        "custodian_equity_holdings": "umb_cef_px",
        "custodian_option_holdings": "umb_cef_px",
        "custodian_treasury_holdings": None,
        "custodian_navs": "umb_cef_nav",
        "cash_table": "umb_cef_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "SPXFIOUP",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.12,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "closed_end_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": True,
        "flex_option_type": "index",
        "has_otc": False,
        "has_treasury": False,
        "overlap_table": "overlap_test",
        "overlap_benchmark_ticker": "SPY",
    },
    "HE3B3": {
        "custodian_equity_holdings": "umb_cef_px",
        "custodian_option_holdings": "umb_cef_px",
        "custodian_treasury_holdings": None,
        "custodian_navs": "umb_cef_nav",
        "cash_table": "umb_cef_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "SPXFIOUP",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.12,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "closed_end_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": True,
        "flex_option_type": "index",
        "has_otc": False,
        "has_treasury": False,
        "overlap_table": "overlap_test",
        "overlap_benchmark_ticker": "SPY",
    },
    "KNG": {
        "custodian_equity_holdings": "bny_us_holdings_v2",
        "custodian_option_holdings": "bny_us_holdings_v2",
        "custodian_treasury_holdings": "bny_us_holdings_v2",
        "custodian_navs": "bny_us_nav_v2",
        "cash_table": "bny_us_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": "tif_frwd_data",
        "flows": "etf_flows",
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "cboe_holdings",
        "index_ticker_join": "SPATI",
        "expense_ratio": 0.0075,
        "option_roll_tenor": "monthly",
        "overwrite": 0.08,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "etf",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": False,
        "flex_option_type": None,
        "has_otc": False,
        "has_treasury": True,
    },
    "KNGIX": {
        "custodian_equity_holdings": "bny_us_holdings_v2",
        "custodian_option_holdings": "bny_us_holdings_v2",
        "custodian_treasury_holdings": "bny_us_holdings_v2",
        "custodian_navs": "ccva_nav",
        "cash_table": "ccva_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": "tif_frwd_data",
        "flows": "etf_flows",
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "cboe_holdings",
        "index_ticker_join": "SPATI",
        "expense_ratio": 0.01,
        "option_roll_tenor": "weekly",
        "overwrite": 0.1,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "mutual_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": False,
        "flex_option_type": None,
        "has_otc": False,
        "has_treasury": True,
    },
    "P20127": {
        "custodian_equity_holdings": "umb_cef_px",
        "custodian_option_holdings": "umb_cef_px",
        "custodian_treasury_holdings": None,
        "custodian_navs": "umb_cef_nav",
        "cash_table": "umb_cef_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "SPXFIOUP",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.15,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "closed_end_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": True,
        "flex_option_type": "index",
        "has_otc": False,
        "has_treasury": False,
        "overlap_table": "overlap_test",
        "overlap_benchmark_ticker": "SPY",
    },
    "P21026": {
        "custodian_equity_holdings": "umb_cef_px",
        "custodian_option_holdings": "umb_cef_px",
        "custodian_treasury_holdings": None,
        "custodian_navs": "umb_cef_nav",
        "cash_table": "umb_cef_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "SPXFIOUP",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.15,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "closed_end_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": True,
        "flex_option_type": "index",
        "has_otc": False,
        "has_treasury": False,
        "overlap_table": "overlap_test",
        "overlap_benchmark_ticker": "SPY",
    },
    "P2726": {
        "custodian_equity_holdings": "umb_cef_px",
        "custodian_option_holdings": "umb_cef_px",
        "custodian_treasury_holdings": None,
        "custodian_navs": "umb_cef_nav",
        "cash_table": "umb_cef_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "SPXFIOUP",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.15,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "closed_end_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": True,
        "flex_option_type": "index",
        "has_otc": False,
        "has_treasury": False,
        "overlap_table": "overlap_test",
        "overlap_benchmark_ticker": "SPY",
    },
    "P30128": {
        "custodian_equity_holdings": "umb_cef_px",
        "custodian_option_holdings": "umb_cef_px",
        "custodian_treasury_holdings": None,
        "custodian_navs": "umb_cef_nav",
        "cash_table": "umb_cef_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "SPXFIOUP",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.15,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "closed_end_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": True,
        "flex_option_type": "index",
        "has_otc": False,
        "has_treasury": False,
        "overlap_table": "overlap_test",
        "overlap_benchmark_ticker": "SPY",
    },
    "P31027": {
        "custodian_equity_holdings": "umb_cef_px",
        "custodian_option_holdings": "umb_cef_px",
        "custodian_treasury_holdings": None,
        "custodian_navs": "umb_cef_nav",
        "cash_table": "umb_cef_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "SPXFIOUP",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.12,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "closed_end_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": True,
        "flex_option_type": "index",
        "has_otc": False,
        "has_treasury": False,
        "overlap_table": "overlap_test",
        "overlap_benchmark_ticker": "SPY",
    },
    "P3727": {
        "custodian_equity_holdings": "umb_cef_px",
        "custodian_option_holdings": "umb_cef_px",
        "custodian_treasury_holdings": None,
        "custodian_navs": "umb_cef_nav",
        "cash_table": "umb_cef_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "SPXFIOUP",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.12,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "closed_end_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": True,
        "flex_option_type": "index",
        "has_otc": False,
        "has_treasury": False,
        "overlap_table": "overlap_test",
        "overlap_benchmark_ticker": "SPY",
    },
    "PD227": {
        "custodian_equity_holdings": None,
        "custodian_option_holdings": None,
        "custodian_treasury_holdings": None,
        "custodian_navs": "socgen_equity_statement",
        "cash_table": "sg_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "SPXFIOUP",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.12,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "private_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": False,
        "flex_option_type": None,
        "has_otc": False,
        "has_treasury": False,
    },
    "PF227": {
        "custodian_equity_holdings": None,
        "custodian_option_holdings": None,
        "custodian_treasury_holdings": None,
        "custodian_navs": "socgen_equity_statement",
        "cash_table": "sg_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "SPXFIOUP",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.12,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "private_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": False,
        "flex_option_type": None,
        "has_otc": False,
        "has_treasury": False,
    },
    "PF27V1": {
        "custodian_equity_holdings": None,
        "custodian_option_holdings": None,
        "custodian_treasury_holdings": None,
        "custodian_navs": "socgen_equity_statement",
        "cash_table": "sg_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "SPXFIOUP",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.16,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "private_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": False,
        "flex_option_type": None,
        "has_otc": False,
        "has_treasury": False,
    },
    "R21126": {
        "custodian_equity_holdings": "umb_cef_px",
        "custodian_option_holdings": "umb_cef_px",
        "custodian_treasury_holdings": None,
        "custodian_navs": "umb_cef_nav",
        "cash_table": "umb_cef_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "nasdaq_pro",
        "index_ticker_join": "RDVI",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.12,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "closed_end_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": True,
        "flex_option_type": "index",
        "has_otc": False,
        "has_treasury": False,
        "overlap_table": "overlap_test",
        "overlap_benchmark_ticker": "SPY",
    },
    "RDVI": {
        "custodian_equity_holdings": "bny_us_holdings_v2",
        "custodian_option_holdings": "bny_us_holdings_v2",
        "custodian_treasury_holdings": "bny_us_holdings_v2",
        "custodian_navs": "bny_us_nav_v2",
        "cash_table": "bny_us_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": "tif_frwd_data",
        "flows": "etf_flows",
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "nasdaq_pro",
        "index_ticker_join": "RDVI",
        "expense_ratio": 0.0075,
        "option_roll_tenor": "weekly",
        "overwrite": 0.08,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "etf",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": False,
        "flex_option_type": None,
        "has_otc": False,
        "has_treasury": True,
    },
    "SDVD": {
        "custodian_equity_holdings": "bny_us_holdings_v2",
        "custodian_option_holdings": "bny_us_holdings_v2",
        "custodian_treasury_holdings": "bny_us_holdings_v2",
        "custodian_navs": "bny_us_nav_v2",
        "cash_table": "bny_us_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": "tif_frwd_data",
        "flows": "etf_flows",
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "nasdaq_pro",
        "index_ticker_join": "SDVD",
        "expense_ratio": 0.0085,
        "option_roll_tenor": "weekly",
        "overwrite": 0.08,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "etf",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": False,
        "flex_option_type": None,
        "has_otc": False,
        "has_treasury": True,
    },
    "TDVI": {
        "custodian_equity_holdings": "bny_us_holdings_v2",
        "custodian_option_holdings": "bny_us_holdings_v2",
        "custodian_treasury_holdings": "bny_us_holdings_v2",
        "custodian_navs": "bny_us_nav_v2",
        "cash_table": "bny_us_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": "tif_frwd_data",
        "flows": "etf_flows",
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "nasdaq_pro",
        "index_ticker_join": "TDVI",
        "expense_ratio": 0.0075,
        "option_roll_tenor": "weekly",
        "overwrite": 0.08,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "etf",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": False,
        "flex_option_type": None,
        "has_otc": False,
        "has_treasury": True,
    },
    "TR2B1": {
        "custodian_equity_holdings": "umb_cef_px",
        "custodian_option_holdings": "umb_cef_px",
        "custodian_treasury_holdings": None,
        "custodian_navs": "umb_cef_nav",
        "cash_table": "umb_cef_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "SPXFIOUP",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.15,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "closed_end_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": True,
        "flex_option_type": "index",
        "has_otc": False,
        "has_treasury": False,
        "overlap_table": "overlap_test",
        "overlap_benchmark_ticker": "SPY",
    },
    "TR2B2": {
        "custodian_equity_holdings": "umb_cef_px",
        "custodian_option_holdings": "umb_cef_px",
        "custodian_treasury_holdings": None,
        "custodian_navs": "umb_cef_nav",
        "cash_table": "umb_cef_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "SPXFIOUP",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.15,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "closed_end_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": True,
        "flex_option_type": "index",
        "has_otc": False,
        "has_treasury": False,
        "overlap_table": "overlap_test",
        "overlap_benchmark_ticker": "SPY",
    },
    "TR2B3": {
        "custodian_equity_holdings": "umb_cef_px",
        "custodian_option_holdings": "umb_cef_px",
        "custodian_treasury_holdings": None,
        "custodian_navs": "umb_cef_nav",
        "cash_table": "umb_cef_cash",
        "vest_equity_holdings": "tif_oms_equity_holdings",
        "vest_options_holdings": "tif_oms_option_holdings",
        "vest_treasury_holdings": "tif_oms_treasury_holdings",
        "basket": None,
        "flows": None,
        "sg_custodian_holdings": "socgen_holdings_statement",
        "index_holdings": "sp_holdings",
        "index_ticker_join": "SPXFIOUP",
        "expense_ratio": 0.0265,
        "option_roll_tenor": "weekly",
        "overwrite": 0.15,
        "option_custodian_assignment": "sg_assignment_statement_v2",
        "vehicle_wrapper": "closed_end_fund",
        "equity_benchmark_index_ticker": None,
        "has_equity": True,
        "has_listed_option": True,
        "has_flex_option": True,
        "flex_option_type": "index",
        "has_otc": False,
        "has_treasury": False,
        "overlap_table": "overlap_test",
        "overlap_benchmark_ticker": "SPY",
    },
}

INDEX_LISTED_OPTION_FUNDS = {"RDVI", "SDVD", "TDVI", "FTCSH", "FDND", "FGSI"}
EXPLICIT_SINGLE_STOCK_LISTED_OPTION_FUNDS = {"KNG", "KNGIX"}

LEGACY_DIVERSIFIED_FUNDS = {
    "KNGIX",
    "KNG",
    "HE3B1",
    "TR2B1",
    "HE3B2",
    "TR2B2",
    "P20127",
    "P21026",
    "P2726",
    "P30128",
    "P31027",
    "P3727",
    "R21126",
}

LEGACY_NON_DIVERSIFIED_FUNDS = {
    "DOGG",
    "FDND",
    "FGSI",
    "FTCSH",
    "FTMIX",
    "RDVI",
    "SDVD",
    "TDVI",
}

for fund, payload in FUND_DEFINITIONS.items():
    has_listed_option = bool(payload.get("has_listed_option"))
    vehicle = (payload.get("vehicle_wrapper") or "").lower()

    if has_listed_option:
        if fund in INDEX_LISTED_OPTION_FUNDS:
            payload["listed_option_type"] = "index"
        elif (
            vehicle in {"closed_end_fund", "private_fund"}
            or fund in EXPLICIT_SINGLE_STOCK_LISTED_OPTION_FUNDS
        ):
            payload["listed_option_type"] = "single_stock"
        else:
            payload["listed_option_type"] = payload.get("listed_option_type") or "single_stock"
    else:
        payload["listed_option_type"] = None

    if vehicle == "private_fund":
        diversification_status = "excluded"
    elif vehicle == "closed_end_fund" or fund in LEGACY_DIVERSIFIED_FUNDS:
        diversification_status = "diversified"
    elif fund in LEGACY_NON_DIVERSIFIED_FUNDS:
        diversification_status = "non-diversified"
    else:
        diversification_status = payload.get("diversification_status") or "non-diversified"

    payload["diversification_status"] = diversification_status


# Convenience lookups derived from the metadata to reduce repeated filters elsewhere.
CLOSED_END_FUNDS = {
    fund
    for fund, payload in FUND_DEFINITIONS.items()
    if (payload.get("vehicle_wrapper") or "").lower() == "closed_end_fund"
}
PRIVATE_FUNDS = {
    fund
    for fund, payload in FUND_DEFINITIONS.items()
    if (payload.get("vehicle_wrapper") or "").lower() == "private_fund"
}
ETF_FUNDS = {
    fund
    for fund, payload in FUND_DEFINITIONS.items()
    if (payload.get("vehicle_wrapper") or "").lower() == "etf"
}

DIVERSIFIED_FUNDS = {
    fund
    for fund, payload in FUND_DEFINITIONS.items()
    if payload.get("diversification_status") == "diversified"
}

NON_DIVERSIFIED_FUNDS = {
    fund
    for fund, payload in FUND_DEFINITIONS.items()
    if payload.get("diversification_status") == "non-diversified"
}

LISTED_INDEX_OPTION_FUNDS = {
    fund
    for fund, payload in FUND_DEFINITIONS.items()
    if payload.get("listed_option_type") == "index"
}

LISTED_SINGLE_STOCK_OPTION_FUNDS = {
    fund
    for fund, payload in FUND_DEFINITIONS.items()
    if payload.get("listed_option_type") == "single_stock"
}